# WelcomeMessage Configuration

# Welcome Message Settings
welcome-message:
  enabled: true
  message: "§6✨ Welcome §e {player.name} §6to the server!"
  broadcast-to-all: true
  broadcast-message: "§e✨ {player.name} §6Join to the server!"
  sender: "§7[§eWelcome§aMessage§7]"

# Title Settings
title:
  enabled: true
  title: "§bWelcome {player.name}!"
  subtitle: "§7Enjoy your stay!"
  fadein: 20
  stay: 60
  fadeout: 20

# Effects
effects:
  sound: true
  particles: true
  sound_type: "XP" # Potion, ShulkerBox, TotemUse, XP, Smoker, pop
  particle-type: "Heart"  # HappyVillager, Heart, Flame, Lava, Portal, Enderman
  particle-count: 12